# Generated by Django 2.0.7 on 2019-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=256)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
    ]
