# Generated by Django 2.0.7 on 2019-07-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(verbose_name='How can we help?'),
        ),
    ]
