# Generated by Django 2.0.7 on 2019-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190701_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(verbose_name='What can we do for you?'),
        ),
    ]
