# Generated by Django 2.0.7 on 2019-07-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190702_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Email',
            new_name='email',
        ),
    ]
